import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/main/header";
import { Poppins } from 'next/font/google';
import Footer from "@/components/main/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['300', '400', '500', '600'],
})


export const metadata: Metadata = {
  title: "COE Caribe IPS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
